### PR TITLE
Fixed Flashcards Storage and Display

### PR DESCRIPTION
**Pull request by saikiransomanagoudar**

### CODE REVIEW

**Comment by saikiransomanagoudar** [comment]
Added Back button by Tanmay inside Flashcard component

**Comment by saikiransomanagoudar** [comment]
Integrated Go Back button in Flashcard component.

**Review by tanmay-sketch — APPROVED** [review]
Looks good to me

**Review by andrewalson — APPROVED** [review]
Looks great, awesome job getting this working Saikiran & Tanmay.

**Pull request merged**
